### PR TITLE
Drop unused ign config

### PR DESCRIPTION
**Pull request by enxebre**
Ignitition config is now consumed by workers from the MCO server

### CODE REVIEW

**Comment by csrwng** [comment]
Thank you much! There's a couple of other places that we should delete as well:

- assets/ignition
- pkg/render/manifests.go - ignitionConfigs() function
- pkg/installer/install.go - generateIgnitionServices() as well as https://github.com/openshift-hive/hypershift-installer/blob/master/pkg/installer/install.go#L81-L84

**Comment by enxebre** [comment]
>There's a couple of other places that we should delete as well...

Thanks done! PTAL.

**Pull request merged**
